import { Country } from "../new-app.interface";

class NewsAPIConstants {
  categoryList: string[] = [
    "business",
    "entertainment",
    "general",
    "health",
    "science",
    "sports",
    "technology",
  ];

  countries: Country[] = [
    { countryShortCode: "ae", countryName: "United Arab Emirates" },
    { countryShortCode: "ar", countryName: "Argentina" },
    { countryShortCode: "at", countryName: "Austria" },
    { countryShortCode: "au", countryName: "Australia" },
    { countryShortCode: "be", countryName: "Belgium" },
    { countryShortCode: "bg", countryName: "Bulgaria" },
    { countryShortCode: "br", countryName: "Brazil" },
    { countryShortCode: "ca", countryName: "Canada" },
    { countryShortCode: "ch", countryName: "Switzerland" },
    { countryShortCode: "cn", countryName: "China" },
    { countryShortCode: "co", countryName: "Colombia" },
    { countryShortCode: "cu", countryName: "Cuba" },
    { countryShortCode: "cz", countryName: "Czech Republic" },
    { countryShortCode: "de", countryName: "Germany" },
    { countryShortCode: "eg", countryName: "Egypt" },
    { countryShortCode: "fr", countryName: "France" },
    { countryShortCode: "gb", countryName: "United Kingdom" },
    { countryShortCode: "gr", countryName: "Greece" },
    { countryShortCode: "hk", countryName: "Hong Kong" },
    { countryShortCode: "hu", countryName: "Hungary" },
    { countryShortCode: "id", countryName: "Indonesia" },
    { countryShortCode: "ie", countryName: "Ireland" },
    { countryShortCode: "il", countryName: "Israel" },
    { countryShortCode: "in", countryName: "India" },
    { countryShortCode: "it", countryName: "Italy" },
    { countryShortCode: "jp", countryName: "Japan" },
    { countryShortCode: "kr", countryName: "South Korea" },
    { countryShortCode: "lt", countryName: "Lithuania" },
    { countryShortCode: "lv", countryName: "Latvia" },
    { countryShortCode: "ma", countryName: "Morocco" },
    { countryShortCode: "mx", countryName: "Mexico" },
    { countryShortCode: "my", countryName: "Malaysia" },
    { countryShortCode: "ng", countryName: "Nigeria" },
    { countryShortCode: "nl", countryName: "Netherlands" },
    { countryShortCode: "no", countryName: "Norway" },
    { countryShortCode: "nz", countryName: "New Zealand" },
    { countryShortCode: "ph", countryName: "Philippines" },
    { countryShortCode: "pl", countryName: "Poland" },
    { countryShortCode: "pt", countryName: "Portugal" },
    { countryShortCode: "ro", countryName: "Romania" },
    { countryShortCode: "ru", countryName: "Russia" },
    { countryShortCode: "sa", countryName: "Saudi Arabia" },
    { countryShortCode: "se", countryName: "Sweden" },
    { countryShortCode: "sg", countryName: "Singapore" },
    { countryShortCode: "sk", countryName: "Slovakia" },
    { countryShortCode: "th", countryName: "Thailand" },
    { countryShortCode: "tr", countryName: "Turkey" },
    { countryShortCode: "tw", countryName: "Taiwan" },
    { countryShortCode: "ua", countryName: "Ukraine" },
    { countryShortCode: "us", countryName: "United States" },
    { countryShortCode: "ve", countryName: "Venezuela" },
    { countryShortCode: "za", countryName: "South Africa" },
  ];

  sortKeys: string[] = ["newest", "oldest", "relevance"];
}

export const NEW_API_CONSTANTS = new NewsAPIConstants();
